# Generated by Django 3.0.6 on 2020-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='g/8~47u\\2h`7qWy', max_length=15, unique=True),
        ),
    ]
