# Generated by Django 3.0.6 on 2020-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200526_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='uuid',
            field=models.CharField(default='oE1(~v=c#9DgsNM', max_length=15, unique=True),
        ),
    ]
