# Generated by Django 3.0.6 on 2020-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200526_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='X732D\\BFO]p>B/v', max_length=15, unique=True),
        ),
    ]
