# Generated by Django 3.0.6 on 2020-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200526_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='rE}"P%rJR\'"qs<b', max_length=15, unique=True),
        ),
    ]
