# Generated by Django 3.0.6 on 2020-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200526_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='CD<u)(;.9bh!xH9', max_length=15, unique=True),
        ),
    ]
