# Generated by Django 3.0.6 on 2020-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200526_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='26a9f31dafe4449ea9e3d9831449c7ef', max_length=40, unique=True),
        ),
    ]
