# Generated by Django 3.0.6 on 2020-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200529_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='256cd04265d34f0eb0d84092ee04dedf', max_length=40, unique=True),
        ),
    ]
